### PR TITLE
Prepare for 2.0.1 release

### PR DESCRIPTION
**Pull request by jbornemann**
@trekawek Can we release 2.0.1 to central?  Thanks

### CODE REVIEW

**Comment by trekawek** [comment]
Sure we can! I just released the `2.0.1`. Thanks for pointing this out :)

PS. SDI uses Maven release plugin which takes care of updating version in the pom.xml, creating tag in git, uploading artifacts to the repository, etc. so there is no need to manually drop the `-SNAPSHOT` from the version number.

**Comment by jbornemann** [comment]
Oh, cool;  Well thanks! :)  This project is really helpful!

**Comment by trekawek** [comment]
I'm glad you find it useful :) Could write a few words about your use case?

**Comment by jbornemann** [comment]
We have AEM pages which almost exclusively contain components that are largely dynamic, and data-driven in nature;  However, some of the page content can, and should still be cached.  To create the best experience, and performance;  we want to shift this responsibility as predominately as possible on our Apache servers.  

In many cases, by replacing teasers with SDI enabled components, we have increased performance by large orders of magnitude :) - especially on earlier IE browsers

Thanks again

**Pull request merged**
